### ISSUE TITLE
Accounts not creating!

### ISSUE THREAD

**Issue by Cupcake-Development** [Elminsterxld/discord-token-generator#3]
Accounts not registering on discord it just generating emails..
Also no output in token.txt

**Comment by Elminsterxld** [comment]
Do you have a photo of the error?

**Comment by Cupcake-Development** [comment]
There's is no error, 

No token us gnerating in token.txt also its not creating account on discord..
I tried to login with the email and password generated in logs but it says no account is registered with this email/password

**Comment by Elminsterxld** [comment]
There could be multiple reasons for this.
1- Do you pass captcha ?
2- After the captcha passes, you have to wait a while for the token to arrive in the log.
3- If the txt does not save even though the token is received, please reload the "fs" module.

**Comment by Cupcake-Development** [comment]
Ohh okay leme try.. Thanks for help
